baseURL: "https://mshoaei.ir"
languageCode: en-us
title: Mohammad's blog
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: false
  minifyOutput: true

taxonomies:
  series: series
  tag: tags

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mohammad's blog
  description: This is where I write about technology and Go
  author: Mohammad Shoaei
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "Home"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Mohammad Shoaei
    subtitle: "Hi, I'm 23 and a Go developer."
    imageUrl: "images/author.jpg"
    imageWidth: 200
    imageHeight: 250
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Series
        url: series

  socialIcons:
    - name: github
      url: "https://github.com/MShoaei"
    - name: twitter
      url: "https://twitter.com/MShoaei13"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: series
      name: Series
      url: /series/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
